/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import agents.AgentsRechercheur;
import agents.AgentsUtilisateur;
import agents.AgentsAdministrateur;
import agents.AgentsBibliotekeur;
import container.RechercheurContainer;
import container.AdministrateurContainer;
import container.BibliotekeurContainer;
import jade.core.AID;
import jade.gui.GuiEvent;
import jade.lang.acl.ACLMessage;
import jade.wrapper.AgentController;
import jade.wrapper.ControllerException;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jc
 */
public class Gui extends javax.swing.JFrame {

    private int etat = 0;

    private Vector listeNouveauInfo = new Vector();
    //private str
    private AgentsUtilisateur agentsUtilisateur = new AgentsUtilisateur();

    public AgentsUtilisateur getAgentsUtilisateur() {
        return agentsUtilisateur;
    }

    public void setAgentsUtilisateur(AgentsUtilisateur agentsUtilisateur) {
        this.agentsUtilisateur = agentsUtilisateur;
    }
    private AdministrateurContainer administrateurDeInfo = new AdministrateurContainer();

    public AdministrateurContainer getAdministrateurDeInfo() {
        return administrateurDeInfo;
    }

    public void setAdministrateurDeInfo(AdministrateurContainer administrateurDeInfo) {
        this.administrateurDeInfo = administrateurDeInfo;
    }

    public void displayMessage(String Message) {
        textMessage.append(Message + "\n");
    }

    public void setComboAgents(Vector<String> comboAgents) {
        this.comboAgentsRechercheurs.removeAllItems();
        this.comboxRechercheurASupprimer.removeAllItems();

        for (int i = 0; i < comboAgents.size(); i++) {
            this.comboAgentsRechercheurs.addItem(comboAgents.elementAt(i));
            this.comboxRechercheurASupprimer.addItem(comboAgents.elementAt(i));
        }

    }

    public void setComboAgentsBibliotekeur(Vector<String> comboAgents) {
        this.comboxListBibliotekeur.removeAllItems();
        this.comboxBibliotekeurASupprimer.removeAllItems();

        for (int i = 0; i < comboAgents.size(); i++) {
            this.comboxListBibliotekeur.addItem(comboAgents.elementAt(i).toString().trim());
            this.comboxBibliotekeurASupprimer.addItem(comboAgents.elementAt(i).toString().trim());
        }

        //System.err.println("size "+comboAgents.size());
    }
    private RechercheurContainer agentRechercheur;
    private BibliotekeurContainer agentBibliotekeur;

    public RechercheurContainer getAgentRechercheur() {
        return agentRechercheur;
    }

    public void setAgentRechercheur(RechercheurContainer agentRechercheur) {
        this.agentRechercheur = agentRechercheur;
    }

    public BibliotekeurContainer getAgentBibliotekeur() {
        return agentBibliotekeur;
    }

    public void setAgentBibliotekeur(BibliotekeurContainer agentBibliotekeur) {
        this.agentBibliotekeur = agentBibliotekeur;
    }

    /**
     * Creates new form Gui
     */
    public Gui() {

        initComponents();
        agentRechercheur = new RechercheurContainer();
        agentBibliotekeur = new BibliotekeurContainer();
        //agentsDistributeur = new AgentsAdministrateur();

        //distributeurDeLivre.CreateAgentDistributeur("distributeur1", null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboxBibliotekeurASupprimer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboxRechercheurASupprimer = new javax.swing.JComboBox<>();
        textCreerRechercheur = new javax.swing.JTextField();
        textCreerBibliotekeur = new javax.swing.JTextField();
        textCreerInformation = new javax.swing.JTextField();
        buttonCreerRechercheur = new javax.swing.JButton();
        buttonCreerBibliotekeur = new javax.swing.JButton();
        buttonCreeInformation = new javax.swing.JButton();
        comboxListInformationASupprimer = new javax.swing.JComboBox<>();
        buttonSupprimerBibliotekeur = new javax.swing.JButton();
        buttonSupprimerRechercheur = new javax.swing.JButton();
        jButtonInfoAsupprimer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboxListBibliotekeur = new javax.swing.JComboBox<>();
        comboxListInformations = new javax.swing.JComboBox<>();
        textPrix = new javax.swing.JTextField();
        buttonAssocierInfoBibliotekeur = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMessage = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboAgentsRechercheurs = new javax.swing.JComboBox<>();
        comboxListesInfosRecherches = new javax.swing.JComboBox<>();
        buttonQuitter = new javax.swing.JButton();
        buttonEnvoyer = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Formulaire de création");

        jLabel2.setText("Rechercheur");

        jLabel3.setText("Bibliotekeur");

        jLabel4.setText("Information");

        buttonCreerRechercheur.setText("Ajouter");
        buttonCreerRechercheur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreerRechercheurActionPerformed(evt);
            }
        });

        buttonCreerBibliotekeur.setText("Ajouter");
        buttonCreerBibliotekeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreerBibliotekeurActionPerformed(evt);
            }
        });

        buttonCreeInformation.setText("Ajouter");
        buttonCreeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreeInformationActionPerformed(evt);
            }
        });

        buttonSupprimerBibliotekeur.setText("Supprimer");
        buttonSupprimerBibliotekeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerBibliotekeurActionPerformed(evt);
            }
        });

        buttonSupprimerRechercheur.setText("Supprimer");
        buttonSupprimerRechercheur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerRechercheurActionPerformed(evt);
            }
        });

        jButtonInfoAsupprimer.setText("Supprimer");
        jButtonInfoAsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoAsupprimerActionPerformed(evt);
            }
        });

        jLabel8.setText("Bibliotekeur");

        jLabel10.setText("Information");

        jLabel11.setText("ValeurPrix");

        buttonAssocierInfoBibliotekeur.setText("Associer");
        buttonAssocierInfoBibliotekeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAssocierInfoBibliotekeurActionPerformed(evt);
            }
        });

        jLabel12.setText("Rechercheur");

        jLabel13.setText("Bibliotekeur");

        jLabel14.setText("Information");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Formulaire de suppression");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Formulaire d'association de livre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Administration");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Commandes");

        textMessage.setEditable(false);
        textMessage.setColumns(20);
        textMessage.setRows(5);
        jScrollPane1.setViewportView(textMessage);

        jLabel16.setText("Rechercheur");

        jLabel17.setText("Informations");

        comboxListesInfosRecherches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxListesInfosRecherchesActionPerformed(evt);
            }
        });

        buttonQuitter.setText("Quitter");
        buttonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitterActionPerformed(evt);
            }
        });

        buttonEnvoyer.setText("Envoyer");
        buttonEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnvoyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonQuitter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonEnvoyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboxListesInfosRecherches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboAgentsRechercheurs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textCreerRechercheur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textCreerBibliotekeur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textCreerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonCreerBibliotekeur)
                                            .addComponent(buttonCreerRechercheur)
                                            .addComponent(buttonCreeInformation))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(comboxBibliotekeurASupprimer, 0, 49, Short.MAX_VALUE)
                                                            .addComponent(comboxRechercheurASupprimer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(comboxListInformationASupprimer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(10, 10, 10)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButtonInfoAsupprimer)
                                                            .addComponent(buttonSupprimerRechercheur)
                                                            .addComponent(buttonSupprimerBibliotekeur)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonAssocierInfoBibliotekeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textPrix)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboxListInformations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboxListBibliotekeur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textCreerRechercheur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboxRechercheurASupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(comboxListBibliotekeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(buttonCreerRechercheur))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buttonSupprimerRechercheur)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCreerBibliotekeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buttonCreerBibliotekeur)
                    .addComponent(comboxBibliotekeurASupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboxListInformations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(buttonSupprimerBibliotekeur))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCreerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(buttonCreeInformation)
                            .addComponent(comboxListInformationASupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInfoAsupprimer)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(textPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAssocierInfoBibliotekeur)
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(comboAgentsRechercheurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comboxListesInfosRecherches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonEnvoyer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonQuitter)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSupprimerBibliotekeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerBibliotekeurActionPerformed
        String nomAgent = comboxBibliotekeurASupprimer.getSelectedItem().toString();
        //System.err.println(" agent ("+nomAgent+")");
        if (!nomAgent.isEmpty()) {
            try {
                comboxBibliotekeurASupprimer.removeItem(nomAgent);
                getAgentBibliotekeur().getAgentContainer().getAgent(nomAgent).kill();
                System.out.println(" suppression réussie ");
                //agentRechercheur
            } catch (ControllerException ex) {
                Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println(" echec de suppression  ");
            }
            // TODO add your handling code here:
        }

    }//GEN-LAST:event_buttonSupprimerBibliotekeurActionPerformed

    private void jButtonInfoAsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoAsupprimerActionPerformed
        // TODO add your handling code here:
        if (!comboxListInformationASupprimer.getSelectedItem().toString().isEmpty()) {
            comboxListInformationASupprimer.removeItem(comboxListInformationASupprimer.getSelectedItem());
        }
    }//GEN-LAST:event_jButtonInfoAsupprimerActionPerformed

    private void buttonAssocierInfoBibliotekeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAssocierInfoBibliotekeurActionPerformed

        //new AID("Vendeurs 1", AID.ISLOCALNAME).

        // TODO add your handling code here:
        String nomAgent = comboxListBibliotekeur.getSelectedItem().toString();
        String info_recherche = comboxListInformations.getSelectedItem().toString();
        String prix = textPrix.getText();


        if (!nomAgent.isEmpty() && !info_recherche.isEmpty() && !prix.isEmpty()) {
            GuiEvent gev = new GuiEvent(this, 2);

            Map<String, Object> params = new HashMap<>();
            params.put("AGENT", nomAgent);
            params.put("INFORMATION", info_recherche);
            params.put("PRIX", prix);

            //Ajout du paramètres
            gev.addParameter(params);

            //Renvoie des paramètres à l'agent consommateur par le biais de la methode onGuiEvent()
            getAgentsUtilisateur().onGuiEvent(gev);
            System.out.println(" ajout info fait avec succès ");
            textPrix.setText("");
        }


    }//GEN-LAST:event_buttonAssocierInfoBibliotekeurActionPerformed

    private void buttonCreerRechercheurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreerRechercheurActionPerformed
        //création de l'agent rechercheur 
        String nouveauRechercheur = textCreerRechercheur.getText().toString();

        if (!nouveauRechercheur.isEmpty()) {
            getAgentRechercheur().createAgentRechercheur(nouveauRechercheur, new Object[]{"SIRI"});
            textCreerRechercheur.setText("");
        }

    }//GEN-LAST:event_buttonCreerRechercheurActionPerformed

    private void buttonCreerBibliotekeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreerBibliotekeurActionPerformed

        String nouveaubibliotekeur = textCreerBibliotekeur.getText().toString();

        if (!nouveaubibliotekeur.isEmpty()) {
            getAgentBibliotekeur().CreateAgentBibliotekeur(nouveaubibliotekeur, new Object[]{"nnn", "1200"});
            textCreerBibliotekeur.setText("");
        }


    }//GEN-LAST:event_buttonCreerBibliotekeurActionPerformed

    private void buttonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitterActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_buttonQuitterActionPerformed

    private void buttonCreeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreeInformationActionPerformed
       
        comboxListInformations.addItem(textCreerInformation.getText().toString());
        comboxListesInfosRecherches.addItem(textCreerInformation.getText().toString());
        comboxListInformationASupprimer.addItem(textCreerInformation.getText().toString());
        textCreerInformation.setText("");

    }//GEN-LAST:event_buttonCreeInformationActionPerformed

    private void comboxListesInfosRecherchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxListesInfosRecherchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxListesInfosRecherchesActionPerformed

    private void buttonEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnvoyerActionPerformed

        String agent = comboAgentsRechercheurs.getSelectedItem().toString();
        String info_recherche = comboxListesInfosRecherches.getSelectedItem().toString();
        displayMessage("Demande de l'information : " + info_recherche + " prise en charge par l'agent : " + comboAgentsRechercheurs.getSelectedItem().toString());

        if (!agent.isEmpty() && !info_recherche.isEmpty()) {
            GuiEvent gev = new GuiEvent(this, 1);

            Map<String, Object> params = new HashMap<>();
            params.put("AGENT", agent);
            params.put("INFORMATION", info_recherche);

            //Ajout du paramètres
            gev.addParameter(params);

            //Renvoie des paramètres à l'agent consommateur par le biais de la methode onGuiEvent()
            getAgentsUtilisateur().onGuiEvent(gev);
        }
    }//GEN-LAST:event_buttonEnvoyerActionPerformed

    private void buttonSupprimerRechercheurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerRechercheurActionPerformed
        // TODO add your handling code here:

        String nomAgent = comboxRechercheurASupprimer.getSelectedItem().toString();

        //System.out.println(" nom agent " + nomAgent);
        //agentAssupprimer.doDelete();

        if (!nomAgent.isEmpty()) {
            try {
                getAgentRechercheur().getAgentContainer().getAgent(nomAgent).kill();
                System.out.println(" suppression réussie ");
                //agentRechercheur
            } catch (ControllerException ex) {
                Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println(" echec de suppression  ");
            }
        }

    }//GEN-LAST:event_buttonSupprimerRechercheurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAssocierInfoBibliotekeur;
    private javax.swing.JButton buttonCreeInformation;
    private javax.swing.JButton buttonCreerBibliotekeur;
    private javax.swing.JButton buttonCreerRechercheur;
    private javax.swing.JButton buttonEnvoyer;
    private javax.swing.JButton buttonQuitter;
    private javax.swing.JButton buttonSupprimerBibliotekeur;
    private javax.swing.JButton buttonSupprimerRechercheur;
    private javax.swing.JComboBox<String> comboAgentsRechercheurs;
    private javax.swing.JComboBox<String> comboxBibliotekeurASupprimer;
    private javax.swing.JComboBox<String> comboxListBibliotekeur;
    private javax.swing.JComboBox<String> comboxListInformationASupprimer;
    private javax.swing.JComboBox<String> comboxListInformations;
    private javax.swing.JComboBox<String> comboxListesInfosRecherches;
    private javax.swing.JComboBox<String> comboxRechercheurASupprimer;
    private javax.swing.JButton jButtonInfoAsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCreerBibliotekeur;
    private javax.swing.JTextField textCreerInformation;
    private javax.swing.JTextField textCreerRechercheur;
    private javax.swing.JTextArea textMessage;
    private javax.swing.JTextField textPrix;
    // End of variables declaration//GEN-END:variables
}
